version: 2.1
jobs:
  build_x86_64:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Docker Login
          command: docker login -u nanananakam -p ${DOCKER_PASSWORD}
      - run:
          name: Docker Build
          command: docker build -t nanananakam/fluentd-s3:x86_64 .
      - run:
          name: Docker Push
          command: docker push nanananakam/fluentd-s3:x86_64
  build_aarch64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Docker Login
          command: docker login -u nanananakam -p ${DOCKER_PASSWORD}
      - run:
          name: Docker Build
          command: docker build -t nanananakam/fluentd-s3:aarch64 .
      - run:
          name: Docker Push
          command: docker push nanananakam/fluentd-s3:aarch64
  push_manifest:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - run:
          name: Docker Login
          command: docker login -u nanananakam -p ${DOCKER_PASSWORD}
      - run:
          name: Create Manifest
          command: docker manifest create nanananakam/fluentd-s3:latest --amend nanananakam/fluentd-s3:x86_64 --amend nanananakam/fluentd-s3:aarch64
      - run:
          name: Push Manifest
          command: docker manifest push --purge nanananakam/fluentd-s3:latest

workflows:
  version: 2
  workflow:
    jobs:
      - build_x86_64
      - build_aarch64
      - push_manifest:
          requires:
            - build_x86_64
            - build_aarch64